common/models/PostCat.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%post_cat}}".
 *
 * @property integer $id
 * @property string $title
 * @property integer $id_lang
 * @property integer $id_user
 * @property integer $created_at
 * @property integer $updated_at
 */
class PostCat extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%post_cat}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_lang', 'id_user', 'created_at', 'updated_at'], 'integer'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('post_cat', 'ID'),
            'title' => Yii::t('post_cat', 'Title'),
            'id_lang' => Yii::t('post_cat', 'Id Lang'),
            'id_user' => Yii::t('post_cat', 'Id User'),
            'created_at' => Yii::t('post_cat', 'Created At'),
            'updated_at' => Yii::t('post_cat', 'Updated At'),
        ];
    }
}

backend/controllers/PostCatController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\PostCat;
use common\models\PostCatSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostCatController implements the CRUD actions for PostCat model.
 */
class PostCatController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PostCat models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostCatSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PostCat model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PostCat model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PostCat();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing PostCat model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PostCat model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PostCat model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PostCat the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PostCat::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post())&&
        $model->setThumbnail(Yii::$app->request->post('User')['thumbnail']) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) &&
        $model->setThumbnail(Yii::$app->request->post('User')['thumbnail']) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::find()->with('thumbnail')->andWhere(['id' => $id])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/PostCatController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Page;
use common\models\PageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\ContentNegotiator;
use yii\web\Response;

class PageController extends \yii\web\Controller
{

  /**
   * @inheritdoc
   */
  public function behaviors()
  {
      return [
          'verbs' => [
              'class' => VerbFilter::className(),
              'actions' => [
                  'autocomplete' => ['GET'],
              ],
          ],
          'bootstrap' => [
            'class' => ContentNegotiator::className(),
              'only' => ['autocomplete'],
              'formats' => [ 'application/json' => Response::FORMAT_JSON ],
                'languages' => [
                  //'ru-RU',
                  //'en-US'
                  Yii::$app->language,
              ],
          ],
      ];
  }

  /**
   * Lists all Page models.
   * @return mixed
   */
  public function actionIndex()
  {
      $searchModel = new PageSearch();
      $params = Yii::$app->request->queryParams;
      $dataProvider = $searchModel->search($params);

      return $this->render('index', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
          'params' => $params,
      ]);
  }

  /**
   * Displays a single Page model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id)
  {
      return $this->render('view', [
          'model' => $this->findModel($id),
      ]);
  }

  /**
   * Displays search results
   * @param string $phrase
   * @param string | array $field
   * @return mixed
   */
  public function actionSearch($term=null,$field=null)
  {
      $searchParams = [];
      $pageModel = new Page();
      $searchModel = new PageSearch();
      if($field=$field?$field:(Yii::$app->request->post('field','title'
      ))){
        if($term=$term?$term:(Yii::$app->request->post('term'))){
          $searchParams['PageSearch'][$field] = $term;
        }
      }

      $dataProvider = $searchModel->search($searchParams);

      return $this->render('search', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
          'term' => $term,
          'url' => Yii::$app->request->url,
          'title' => Yii::t('page', 'Search'),
          'radioList' => ['id'=>'id','id_lang'=>'id_lang','title'=>'title','keywords'=>'keywords'],//$pageModel::attributeLabels(),
          'field' => $field,
      ]);
  }

  /**
   * Displays ajax results for autocomplete purpose
   * @param string $term
   * @return mixed
   */
  public function actionAutocomplete($term)
  {
    $field=Yii::$app->request->get('field','title');
    return Page::find()
      //->select(['id as value', 'title as label'])
      //->select(['title as value', 'title as label'])
      //->andFilterWhere(['like', 'title', Yii::$app->request->get('term')])
      ->select([$field.' as value', $field.' as label'])
      ->andFilterWhere(['like', $field, Yii::$app->request->get('term')])
      ->distinct()
      ->asArray()
      ->all();
  }

  /**
   * Finds the Page model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Page the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
      if (($model = Page::findOne($id)) !== null) {
          return $model;
      } else {
          throw new NotFoundHttpException('The requested page does not exist.');
      }
  }

}

frontend/views/post-cat/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\PageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('page', 'Pages');
$this->params['breadcrumbs'][] = $this->title;
$this->params['leftMenu'] = isset($leftMenu)?$leftMenu:null;
?>
<div class="page-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            ['attribute' => 'title',
              'content' => function($data){
                return Html::a($data['title'],Url::toRoute($data['id']));
              }
            ],
            'id_lang',
            'keywords',
            ['label' => Yii::t('common', 'Thumbnail image'), 'content' => function($data){
               //$res =
               if(!empty($data['thumbnail']['thumbs'])){
                 $res = @unserialize($data['thumbnail']['thumbs']);
                 if(isset($res['small'])){
                   $res = $res['small'];
                 }
               }
               else{
                 $res = !empty($data['thumbnail']['url'])?$data['thumbnail']['url']:null;
               }
               if($res){
                 $res = Html::img($res);
               }
              return $res;
            }],
            //'content:ntext',
            // 'id_user',
            // 'created_at',
            // 'updated_at',

            /*['class' => 'yii\grid\ActionColumn',
              'template' => '{view}',
            ],*/
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

frontend/views/post-cat/search.php
<?php
/* @var $this yii\web\View */
use yii\jui\AutoComplete;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\grid\GridView;
use yii\widgets\Pjax;

$this->title = $title;
$this->params['breadcrumbs'][] = ['url' => '/page','label' => Yii::t('page','Page')];
$this->params['breadcrumbs'][] = $this->title;
$this->params['leftMenu'] = isset($leftMenu)?$leftMenu:null;
?>
<h1><?= $title ?></h1>

<?php

echo Html::beginForm($url,'post');

echo AutoComplete::widget([
  'name' => 'term',
  'value' => $term,
  'options' => [],
  'clientOptions' => [
    //'source' => Url::toRoute('autocomplete'),
    'source' =>  new JsExpression('function(request,response){
      field=jQuery(document.getElementById("field_radio")).find("input:checked").val();
      if(!field){
        field = "title";
      }
      jQuery.get(
      "'.Url::toRoute('autocomplete').'",
      {term:request.term,field:field},
      function(data){response(data)}
    );
  }'),
    'dataType' => 'json',
    'autoFill' => true,
    'minLength' => 1,
    'select' => new JsExpression('function(event, ui) {
        this.value = ui.item.label;
    }'),
  ],

]);
echo Html::radioList('field',$field, $radioList, ['id' => 'field_radio']);
echo Html::submitButton(Yii::t('common','Search'));
echo Html::endForm();
?>

<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            ['attribute' => 'title',
              'content' => function($data){
                return Html::a($data['title'],Url::toRoute($data['id']));
              }
            ],
            'id_lang',
            'keywords',
            ['label' => Yii::t('common', 'Thumbnail image'), 'content' => function($data){
               //$res =
               if(!empty($data['thumbnail']['thumbs'])){
                 $res = @unserialize($data['thumbnail']['thumbs']);
                 if(isset($res['small'])){
                   $res = $res['small'];
                 }
               }
               else{
                 $res = !empty($data['thumbnail']['url'])?$data['thumbnail']['url']:null;
               }
               if($res){
                 $res = Html::img($res);
               }
              return $res;
            }],
            //'content:ntext',
            // 'id_user',
            // 'created_at',
            // 'updated_at',

            /*['class' => 'yii\grid\ActionColumn',
              'template' => '{view}',
            ],*/
        ],
        'filterPosition' => '',
    ]); ?>
<?php Pjax::end(); ?>

frontend/views/post-cat/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Page */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('page', 'Pages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['leftMenu'] = isset($leftMenu)?$leftMenu:null;
?>
<div class="page-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'id_lang',
            'keywords',
            ['label' => Yii::t('common', 'Thumbnail image'), 'value' => (!empty($model->thumbnail)?(Html::img($model->thumbnail->getThumbUrl('medium'))):''), 'format' => 'html'],
            'content:html',
            ['label' => Yii::t('common', 'Created by'), 'value' => (!empty($model->user)?(Html::a($model->user->username, Url::toRoute(['/user/view', 'id' => $model->id_user]))):''), 'format' => 'html'],
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>